name: Build macOS Executable

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build the executable
      run: pyinstaller --onefile --windowed --hidden-import=openpyxl.cell._writer YOUNGO_election_evaluation.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-executable
        path: dist/YOUNGO_election_evaluation
